apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-ingress
spec:
  tls:
  - hosts:
    - {{ .Values.appUrl }}
  rules:
  - host: {{ .Values.appUrl }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "helloworld.name" . }}-service
            port:
              number: 80
